# Deploy da aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: app-python:v1
        imagePullPolicy: Never 
        ports:
        - containerPort: 5000
        env:
        # Carrega a variável de ambiente APP_MODE do ConfigMap
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: configmap-app
              key: APP_MODE
        - name: DB_HOST
          value: "service-postgres"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: POSTGRES_PASSWORD
---
# Service para expor a aplicação Python
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  type: NodePort 
  selector:
    app: python-app 
  ports:
    - protocol: TCP
      port: 5000       
      targetPort: 5000


# By: Rodrigo Souza 
